version: "3"
services:
  web:
    # replace username/repo:tag with your name and image details
    image: "guppytrain/get-started:a00"
    deploy:
      replicas: 3 
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "4000:80"
    networks:
      - webnet
    # key: SWMTKN-1-49uzsczq5mrsb0zsd5o39tcjwwb7ucu2g7766hbgavusrecbsj-6kjewnj853zdx557tb4xkhjip
networks:
  webnet:

